services:
  - type: web
    name: pdf-yarat
    env: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health 